<?php

use Illuminate\Database\Seeder;

class CountrieTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countrie')->truncate();
        
        DB::table('countrie')->insert(['iso'=> 'AF','name' => 'Afganistán']);
        DB::table('countrie')->insert(['iso'=> 'AX','name' => 'Islas Gland']);
        DB::table('countrie')->insert(['iso'=> 'AL','name' => 'Albania']);
        DB::table('countrie')->insert(['iso'=> 'DE','name' => 'Alemania']);
        DB::table('countrie')->insert(['iso'=> 'AD','name' => 'Andorra']);
        DB::table('countrie')->insert(['iso'=> 'AO','name' => 'Angola']);
        DB::table('countrie')->insert(['iso'=> 'AI','name' => 'Anguilla']);
        DB::table('countrie')->insert(['iso'=> 'AQ','name' => 'Antártida']);
        DB::table('countrie')->insert(['iso'=> 'AG','name' => 'Antigua y Barbuda']);
        DB::table('countrie')->insert(['iso'=> 'AN','name' => 'Antillas Holandesas']);
        DB::table('countrie')->insert(['iso'=> 'SA','name' => 'Arabia Saudí']);
        DB::table('countrie')->insert(['iso'=> 'DZ','name' => 'Argelia']);
        DB::table('countrie')->insert(['iso'=> 'AR','name' => 'Argentina']);
        DB::table('countrie')->insert(['iso'=> 'AM','name' => 'Armenia']);
        DB::table('countrie')->insert(['iso'=> 'AW','name' => 'Aruba']);
        DB::table('countrie')->insert(['iso'=> 'AU','name' => 'Australia']);
        DB::table('countrie')->insert(['iso'=> 'AT','name' => 'Austria']);
        DB::table('countrie')->insert(['iso'=> 'AZ','name' => 'Azerbaiyán']);
        DB::table('countrie')->insert(['iso'=> 'BS','name' => 'Bahamas']);
        DB::table('countrie')->insert(['iso'=> 'BH','name' => 'Bahréin']);
        DB::table('countrie')->insert(['iso'=> 'BD','name' => 'Bangladesh']);
        DB::table('countrie')->insert(['iso'=> 'BB','name' => 'Barbados']);
        DB::table('countrie')->insert(['iso'=> 'BY','name' => 'Bielorrusia']);
        DB::table('countrie')->insert(['iso'=> 'BE','name' => 'Bélgica']);
        DB::table('countrie')->insert(['iso'=> 'BZ','name' => 'Belice']);
        DB::table('countrie')->insert(['iso'=> 'BJ','name' => 'Benin']);
        DB::table('countrie')->insert(['iso'=> 'BM','name' => 'Bermudas']);
        DB::table('countrie')->insert(['iso'=> 'BT','name' => 'Bhután']);
        DB::table('countrie')->insert(['iso'=> 'BO','name' => 'Bolivia']);
        DB::table('countrie')->insert(['iso'=> 'BA','name' => 'Bosnia y Herzegovina']);
        DB::table('countrie')->insert(['iso'=> 'BW','name' => 'Botsuana']);
        DB::table('countrie')->insert(['iso'=> 'BV','name' => 'Isla Bouvet']);
        DB::table('countrie')->insert(['iso'=> 'BR','name' => 'Brasil']);
        DB::table('countrie')->insert(['iso'=> 'BN','name' => 'Brunéi']);
        DB::table('countrie')->insert(['iso'=> 'BG','name' => 'Bulgaria']);
        DB::table('countrie')->insert(['iso'=> 'BF','name' => 'Burkina Faso']);
        DB::table('countrie')->insert(['iso'=> 'BI','name' => 'Burundi']);
        DB::table('countrie')->insert(['iso'=> 'CV','name' => 'Cabo Verde']);
        DB::table('countrie')->insert(['iso'=> 'KY','name' => 'Islas Caimán']);
        DB::table('countrie')->insert(['iso'=> 'KH','name' => 'Camboya']);
        DB::table('countrie')->insert(['iso'=> 'CM','name' => 'Camerún']);
        DB::table('countrie')->insert(['iso'=> 'CA','name' => 'Canadá']);
        DB::table('countrie')->insert(['iso'=> 'CF','name' => 'República Centroafricana']);
        DB::table('countrie')->insert(['iso'=> 'TD','name' => 'Chad']);
        DB::table('countrie')->insert(['iso'=> 'CZ','name' => 'República Checa']);
        DB::table('countrie')->insert(['iso'=> 'CL','name' => 'Chile']);
        DB::table('countrie')->insert(['iso'=> 'CN','name' => 'China']);
        DB::table('countrie')->insert(['iso'=> 'CY','name' => 'Chipre']);
        DB::table('countrie')->insert(['iso'=> 'CX','name' => 'Isla de Navidad']);
        DB::table('countrie')->insert(['iso'=> 'VA','name' => 'Ciudad del Vaticano']);
        DB::table('countrie')->insert(['iso'=> 'CC','name' => 'Islas Cocos']);
        DB::table('countrie')->insert(['iso'=> 'CO','name' => 'Colombia']);
        DB::table('countrie')->insert(['iso'=> 'KM','name' => 'Comoras']);
        DB::table('countrie')->insert(['iso'=> 'CD','name' => 'República Democrática del Congo']);
        DB::table('countrie')->insert(['iso'=> 'CG','name' => 'Congo']);
        DB::table('countrie')->insert(['iso'=> 'CK','name' => 'Islas Cook']);
        DB::table('countrie')->insert(['iso'=> 'KP','name' => 'Corea del Norte']);
        DB::table('countrie')->insert(['iso'=> 'KR','name' => 'Corea del Sur']);
        DB::table('countrie')->insert(['iso'=> 'CI','name' => 'Costa de Marfil']);
        DB::table('countrie')->insert(['iso'=> 'CR','name' => 'Costa Rica']);
        DB::table('countrie')->insert(['iso'=> 'HR','name' => 'Croacia']);
        DB::table('countrie')->insert(['iso'=> 'CU','name' => 'Cuba']);
        DB::table('countrie')->insert(['iso'=> 'DK','name' => 'Dinamarca']);
        DB::table('countrie')->insert(['iso'=> 'DM','name' => 'Dominica']);
        DB::table('countrie')->insert(['iso'=> 'DO','name' => 'República Dominicana']);
        DB::table('countrie')->insert(['iso'=> 'EC','name' => 'Ecuador']);
        DB::table('countrie')->insert(['iso'=> 'EG','name' => 'Egipto']);
        DB::table('countrie')->insert(['iso'=> 'SV','name' => 'El Salvador']);
        DB::table('countrie')->insert(['iso'=> 'AE','name' => 'Emiratos Árabes Unidos']);
        DB::table('countrie')->insert(['iso'=> 'ER','name' => 'Eritrea']);
        DB::table('countrie')->insert(['iso'=> 'SK','name' => 'Eslovaquia']);
        DB::table('countrie')->insert(['iso'=> 'SI','name' => 'Eslovenia']);
        DB::table('countrie')->insert(['iso'=> 'ES','name' => 'España']);
        DB::table('countrie')->insert(['iso'=> 'UM','name' => 'Islas ultramarinas de Estados Unidos']);
        DB::table('countrie')->insert(['iso'=> 'US','name' => 'Estados Unidos']);
        DB::table('countrie')->insert(['iso'=> 'EE','name' => 'Estonia']);
        DB::table('countrie')->insert(['iso'=> 'ET','name' => 'Etiopía']);
        DB::table('countrie')->insert(['iso'=> 'FO','name' => 'Islas Feroe']);
        DB::table('countrie')->insert(['iso'=> 'PH','name' => 'Filipinas']);
        DB::table('countrie')->insert(['iso'=> 'FI','name' => 'Finlandia']);
        DB::table('countrie')->insert(['iso'=> 'FJ','name' => 'Fiyi']);
        DB::table('countrie')->insert(['iso'=> 'FR','name' => 'Francia']);
        DB::table('countrie')->insert(['iso'=> 'GA','name' => 'Gabón']);
        DB::table('countrie')->insert(['iso'=> 'GM','name' => 'Gambia']);
        DB::table('countrie')->insert(['iso'=> 'GE','name' => 'Georgia']);
        DB::table('countrie')->insert(['iso'=> 'GS','name' => 'Islas Georgias del Sur y Sandwich del Sur']);
        DB::table('countrie')->insert(['iso'=> 'GH','name' => 'Ghana']);
        DB::table('countrie')->insert(['iso'=> 'GI','name' => 'Gibraltar']);
        DB::table('countrie')->insert(['iso'=> 'GD','name' => 'Granada']);
        DB::table('countrie')->insert(['iso'=> 'GR','name' => 'Grecia']);
        DB::table('countrie')->insert(['iso'=> 'GL','name' => 'Groenlandia']);
        DB::table('countrie')->insert(['iso'=> 'GP','name' => 'Guadalupe']);
        DB::table('countrie')->insert(['iso'=> 'GU','name' => 'Guam']);
        DB::table('countrie')->insert(['iso'=> 'GT','name' => 'Guatemala']);
        DB::table('countrie')->insert(['iso'=> 'GF','name' => 'Guayana Francesa']);
        DB::table('countrie')->insert(['iso'=> 'GN','name' => 'Guinea']);
        DB::table('countrie')->insert(['iso'=> 'GQ','name' => 'Guinea Ecuatorial']);
        DB::table('countrie')->insert(['iso'=> 'GW','name' => 'Guinea-Bissau']);
        DB::table('countrie')->insert(['iso'=> 'GY','name' => 'Guyana']);
        DB::table('countrie')->insert(['iso'=> 'HT','name' => 'Haití']);
        DB::table('countrie')->insert(['iso'=> 'HM','name' => 'Islas Heard y McDonald']);
        DB::table('countrie')->insert(['iso'=> 'HN','name' => 'Honduras']);
        DB::table('countrie')->insert(['iso'=> 'HK','name' => 'Hong Kong']);
        DB::table('countrie')->insert(['iso'=> 'HU','name' => 'Hungría']);
        DB::table('countrie')->insert(['iso'=> 'IN','name' => 'India']);
        DB::table('countrie')->insert(['iso'=> 'ID','name' => 'Indonesia']);
        DB::table('countrie')->insert(['iso'=> 'IR','name' => 'Irán']);
        DB::table('countrie')->insert(['iso'=> 'IQ','name' => 'Iraq']);
        DB::table('countrie')->insert(['iso'=> 'IE','name' => 'Irlanda']);
        DB::table('countrie')->insert(['iso'=> 'IS','name' => 'Islandia']);
        DB::table('countrie')->insert(['iso'=> 'IL','name' => 'Israel']);
        DB::table('countrie')->insert(['iso'=> 'IT','name' => 'Italia']);
        DB::table('countrie')->insert(['iso'=> 'JM','name' => 'Jamaica']);
        DB::table('countrie')->insert(['iso'=> 'JP','name' => 'Japón']);
        DB::table('countrie')->insert(['iso'=> 'JO','name' => 'Jordania']);
        DB::table('countrie')->insert(['iso'=> 'KZ','name' => 'Kazajstán']);
        DB::table('countrie')->insert(['iso'=> 'KE','name' => 'Kenia']);
        DB::table('countrie')->insert(['iso'=> 'KG','name' => 'Kirguistán']);
        DB::table('countrie')->insert(['iso'=> 'KI','name' => 'Kiribati']);
        DB::table('countrie')->insert(['iso'=> 'KW','name' => 'Kuwait']);
        DB::table('countrie')->insert(['iso'=> 'LA','name' => 'Laos']);
        DB::table('countrie')->insert(['iso'=> 'LS','name' => 'Lesotho']);
        DB::table('countrie')->insert(['iso'=> 'LV','name' => 'Letonia']);
        DB::table('countrie')->insert(['iso'=> 'LB','name' => 'Líbano']);
        DB::table('countrie')->insert(['iso'=> 'LR','name' => 'Liberia']);
        DB::table('countrie')->insert(['iso'=> 'LY','name' => 'Libia']);
        DB::table('countrie')->insert(['iso'=> 'LI','name' => 'Liechtenstein']);
        DB::table('countrie')->insert(['iso'=> 'LT','name' => 'Lituania']);
        DB::table('countrie')->insert(['iso'=> 'LU','name' => 'Luxemburgo']);
        DB::table('countrie')->insert(['iso'=> 'MO','name' => 'Macao']);
        DB::table('countrie')->insert(['iso'=> 'MK','name' => 'ARY Macedonia']);
        DB::table('countrie')->insert(['iso'=> 'MG','name' => 'Madagascar']);
        DB::table('countrie')->insert(['iso'=> 'MY','name' => 'Malasia']);
        DB::table('countrie')->insert(['iso'=> 'MW','name' => 'Malawi']);
        DB::table('countrie')->insert(['iso'=> 'MV','name' => 'Maldivas']);
        DB::table('countrie')->insert(['iso'=> 'ML','name' => 'Malí']);
        DB::table('countrie')->insert(['iso'=> 'MT','name' => 'Malta']);
        DB::table('countrie')->insert(['iso'=> 'FK','name' => 'Islas Malvinas']);
        DB::table('countrie')->insert(['iso'=> 'MP','name' => 'Islas Marianas del Norte']);
        DB::table('countrie')->insert(['iso'=> 'MA','name' => 'Marruecos']);
        DB::table('countrie')->insert(['iso'=> 'MH','name' => 'Islas Marshall']);
        DB::table('countrie')->insert(['iso'=> 'MQ','name' => 'Martinica']);
        DB::table('countrie')->insert(['iso'=> 'MU','name' => 'Mauricio']);
        DB::table('countrie')->insert(['iso'=> 'MR','name' => 'Mauritania']);
        DB::table('countrie')->insert(['iso'=> 'YT','name' => 'Mayotte']);
        DB::table('countrie')->insert(['iso'=> 'MX','name' => 'México']);
        DB::table('countrie')->insert(['iso'=> 'FM','name' => 'Micronesia']);
        DB::table('countrie')->insert(['iso'=> 'MD','name' => 'Moldavia']);
        DB::table('countrie')->insert(['iso'=> 'MC','name' => 'Mónaco']);
        DB::table('countrie')->insert(['iso'=> 'MN','name' => 'Mongolia']);
        DB::table('countrie')->insert(['iso'=> 'MS','name' => 'Montserrat']);
        DB::table('countrie')->insert(['iso'=> 'MZ','name' => 'Mozambique']);
        DB::table('countrie')->insert(['iso'=> 'MM','name' => 'Myanmar']);
        DB::table('countrie')->insert(['iso'=> 'NA','name' => 'Namibia']);
        DB::table('countrie')->insert(['iso'=> 'NR','name' => 'Nauru']);
        DB::table('countrie')->insert(['iso'=> 'NP','name' => 'Nepal']);
        DB::table('countrie')->insert(['iso'=> 'NI','name' => 'Nicaragua']);
        DB::table('countrie')->insert(['iso'=> 'NE','name' => 'Níger']);
        DB::table('countrie')->insert(['iso'=> 'NG','name' => 'Nigeria']);
        DB::table('countrie')->insert(['iso'=> 'NU','name' => 'Niue']);
        DB::table('countrie')->insert(['iso'=> 'NF','name' => 'Isla Norfolk']);
        DB::table('countrie')->insert(['iso'=> 'NO','name' => 'Noruega']);
        DB::table('countrie')->insert(['iso'=> 'NC','name' => 'Nueva Caledonia']);
        DB::table('countrie')->insert(['iso'=> 'NZ','name' => 'Nueva Zelanda']);
        DB::table('countrie')->insert(['iso'=> 'OM','name' => 'Omán']);
        DB::table('countrie')->insert(['iso'=> 'NL','name' => 'Países Bajos']);
        DB::table('countrie')->insert(['iso'=> 'PK','name' => 'Pakistán']);
        DB::table('countrie')->insert(['iso'=> 'PW','name' => 'Palau']);
        DB::table('countrie')->insert(['iso'=> 'PS','name' => 'Palestina']);
        DB::table('countrie')->insert(['iso'=> 'PA','name' => 'Panamá']);
        DB::table('countrie')->insert(['iso'=> 'PG','name' => 'Papúa Nueva Guinea']);
        DB::table('countrie')->insert(['iso'=> 'PY','name' => 'Paraguay']);
        DB::table('countrie')->insert(['iso'=> 'PE','name' => 'Perú']);
        DB::table('countrie')->insert(['iso'=> 'PN','name' => 'Islas Pitcairn']);
        DB::table('countrie')->insert(['iso'=> 'PF','name' => 'Polinesia Francesa']);
        DB::table('countrie')->insert(['iso'=> 'PL','name' => 'Polonia']);
        DB::table('countrie')->insert(['iso'=> 'PT','name' => 'Portugal']);
        DB::table('countrie')->insert(['iso'=> 'PR','name' => 'Puerto Rico']);
        DB::table('countrie')->insert(['iso'=> 'QA','name' => 'Qatar']);
        DB::table('countrie')->insert(['iso'=> 'GB','name' => 'Reino Unido']);
        DB::table('countrie')->insert(['iso'=> 'RE','name' => 'Reunión']);
        DB::table('countrie')->insert(['iso'=> 'RW','name' => 'Ruanda']);
        DB::table('countrie')->insert(['iso'=> 'RO','name' => 'Rumania']);
        DB::table('countrie')->insert(['iso'=> 'RU','name' => 'Rusia']);
        DB::table('countrie')->insert(['iso'=> 'EH','name' => 'Sahara Occidental']);
        DB::table('countrie')->insert(['iso'=> 'SB','name' => 'Islas Salomón']);
        DB::table('countrie')->insert(['iso'=> 'WS','name' => 'Samoa']);
        DB::table('countrie')->insert(['iso'=> 'AS','name' => 'Samoa Americana']);
        DB::table('countrie')->insert(['iso'=> 'KN','name' => 'San Cristóbal y Nevis']);
        DB::table('countrie')->insert(['iso'=> 'SM','name' => 'San Marino']);
        DB::table('countrie')->insert(['iso'=> 'PM','name' => 'San Pedro y Miquelón']);
        DB::table('countrie')->insert(['iso'=> 'VC','name' => 'San Vicente y las Granadinas']);
        DB::table('countrie')->insert(['iso'=> 'SH','name' => 'Santa Helena']);
        DB::table('countrie')->insert(['iso'=> 'LC','name' => 'Santa Lucía']);
        DB::table('countrie')->insert(['iso'=> 'ST','name' => 'Santo Tomé y Príncipe']);
        DB::table('countrie')->insert(['iso'=> 'SN','name' => 'Senegal']);
        DB::table('countrie')->insert(['iso'=> 'CS','name' => 'Serbia y Montenegro']);
        DB::table('countrie')->insert(['iso'=> 'SC','name' => 'Seychelles']);
        DB::table('countrie')->insert(['iso'=> 'SL','name' => 'Sierra Leona']);
        DB::table('countrie')->insert(['iso'=> 'SG','name' => 'Singapur']);
        DB::table('countrie')->insert(['iso'=> 'SY','name' => 'Siria']);
        DB::table('countrie')->insert(['iso'=> 'SO','name' => 'Somalia']);
        DB::table('countrie')->insert(['iso'=> 'LK','name' => 'Sri Lanka']);
        DB::table('countrie')->insert(['iso'=> 'SZ','name' => 'Suazilandia']);
        DB::table('countrie')->insert(['iso'=> 'ZA','name' => 'Sudáfrica']);
        DB::table('countrie')->insert(['iso'=> 'SD','name' => 'Sudán']);
        DB::table('countrie')->insert(['iso'=> 'SE','name' => 'Suecia']);
        DB::table('countrie')->insert(['iso'=> 'CH','name' => 'Suiza']);
        DB::table('countrie')->insert(['iso'=> 'SR','name' => 'Surinam']);
        DB::table('countrie')->insert(['iso'=> 'SJ','name' => 'Svalbard y Jan Mayen']);
        DB::table('countrie')->insert(['iso'=> 'TH','name' => 'Tailandia']);
        DB::table('countrie')->insert(['iso'=> 'TW','name' => 'Taiwán']);
        DB::table('countrie')->insert(['iso'=> 'TZ','name' => 'Tanzania']);
        DB::table('countrie')->insert(['iso'=> 'TJ','name' => 'Tayikistán']);
        DB::table('countrie')->insert(['iso'=> 'IO','name' => 'Territorio Británico del Océano Índico']);
        DB::table('countrie')->insert(['iso'=> 'TF','name' => 'Territorios Australes Franceses']);
        DB::table('countrie')->insert(['iso'=> 'TL','name' => 'Timor Oriental']);
        DB::table('countrie')->insert(['iso'=> 'TG','name' => 'Togo']);
        DB::table('countrie')->insert(['iso'=> 'TK','name' => 'Tokelau']);
        DB::table('countrie')->insert(['iso'=> 'TO','name' => 'Tonga']);
        DB::table('countrie')->insert(['iso'=> 'TT','name' => 'Trinidad y Tobago']);
        DB::table('countrie')->insert(['iso'=> 'TN','name' => 'Túnez']);
        DB::table('countrie')->insert(['iso'=> 'TC','name' => 'Islas Turcas y Caicos']);
        DB::table('countrie')->insert(['iso'=> 'TM','name' => 'Turkmenistán']);
        DB::table('countrie')->insert(['iso'=> 'TR','name' => 'Turquía']);
        DB::table('countrie')->insert(['iso'=> 'TV','name' => 'Tuvalu']);
        DB::table('countrie')->insert(['iso'=> 'UA','name' => 'Ucrania']);
        DB::table('countrie')->insert(['iso'=> 'UG','name' => 'Uganda']);
        DB::table('countrie')->insert(['iso'=> 'UY','name' => 'Uruguay']);
        DB::table('countrie')->insert(['iso'=> 'UZ','name' => 'Uzbekistán']);
        DB::table('countrie')->insert(['iso'=> 'VU','name' => 'Vanuatu']);
        DB::table('countrie')->insert(['iso'=> 'VE','name' => 'Venezuela']);
        DB::table('countrie')->insert(['iso'=> 'VN','name' => 'Vietnam']);
        DB::table('countrie')->insert(['iso'=> 'VG','name' => 'Islas Vírgenes Británicas']);
        DB::table('countrie')->insert(['iso'=> 'VI','name' => 'Islas Vírgenes de los Estados Unidos']);
        DB::table('countrie')->insert(['iso'=> 'WF','name' => 'Wallis y Futuna']);
        DB::table('countrie')->insert(['iso'=> 'YE','name' => 'Yemen']);
        DB::table('countrie')->insert(['iso'=> 'DJ','name' => 'Yibuti']);
        DB::table('countrie')->insert(['iso'=> 'ZM','name' => 'Zambia']);
        DB::table('countrie')->insert(['iso'=> 'ZW','name' => 'Zimbabue']);
        
    }
}
